<?php
/**
 * @file
 * Code for the pece_ethnographic_file feature.
 */

include_once 'pece_ethnographic_file.features.inc';

/**
 * Implements hook_form_ID_alter().
 */
function pece_ethnographic_file_form_pece_ethnographic_file_node_form_alter(&$form, &$form_state) {
    // @TODO: show URI field once API is available.
    $form['field_pece_uri']['#access'] = FALSE;
    // Hide the comment settings fieldset.
    $form['comment_settings']['#access'] = FALSE;
}